# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    variables:
       tags: $(Build.BuildId)

    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)'
        repository: '$(AWS_ECR_REPOSITORY_URI)'
        tags: |
          $(Build.BuildId)
          


    - task: CopyFiles@2
      inputs:
        Contents: 'eks-deploy-from-ecr.yaml'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
          
    - task: ECRPushImage@1
      inputs:
        awsCredentials: '$(AWS_CREDENTIALS)'
        regionName: '$(AWS_REGION)'
        imageSource: 'imagename'
        sourceImageName: '$(AWS_ECR_REPOSITORY_URI)'
        sourceImageTag: '$(Build.BuildId)'
        repositoryName: '$(AWS_ECR_REPOSITORY_NAME)'
        pushTag: '$(Build.BuildId)'
        
        
